export const colors = {
  light: {
    commonBg: "#FFF",
    commonBorder: "#C5C5C5",
    headerBorder: "#B2B2B2",
    headerBackground: "#FFFFFF",
    headerTintColor: "#FFFFFF",
    headerTitleColor: "#000000",
    backgroundColor: "#FFFFFF",
    borderColor: "#e7e3eb",
    defaultText: "#280d5f",
    inactiveColor: "#7a6eaa",
    disabledButton: "#B3B3B3",
    primaryColor: "#1fc7d4",
    infoColor: "#1d74f5",
    dangerColor: "#f5455c",
    warningColor: "#ffbb00",
    successColor: "#0F6A4B",
    buttonText: "#ffffff",
    buttonColor: "#1fc7d4",
    faqTitle: "#7645d9",
    priceColor: "#ffb237",
    inactiveTab: "#d7caec",
    activeTab: "#7a6eaa",
    disableBackground: "#FAF9FA",
    disableText: "#BDC2C4",
    bgHeader: "#f2ecf2",
    bgSelect: "#FFF",
  },
  dark: {
    commonBg: "#000",
    commonBorder: "#CCC",
    headerBorder: "#B2B2B2",
    headerBackground: "#FFFFFF",
    headerTintColor: "#FFFFFF",
    headerTitleColor: "#000000",
    backgroundColor: "#FFFFFF",
    borderColor: "#e7e3eb",
    defaultText: "#280d5f",
    inactiveColor: "#7a6eaa",
    disabledButton: "#B3B3B3",
    primaryColor: "#1fc7d4",
    infoColor: "#1d74f5",
    dangerColor: "#f5455c",
    warningColor: "#ffbb00",
    successColor: "#0F6A4B",
    buttonText: "#ffffff",
    buttonColor: "#1fc7d4",
    faqTitle: "#7645d9",
    priceColor: "#ffb237",
    inactiveTab: "#d7caec",
    activeTab: "#7a6eaa",
    disableBackground: "#FAF9FA",
    disableText: "#BDC2C4",
    bgHeader: "#f2ecf2",
    bgSelect: "#FFF",
  },
};

export const themes = colors;
